
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-17T19:40:05+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3c3d1533a8ef09dad6987e06fc5375867c18c529",
 "version": "0.0.32+6.g3c3d153"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
